version: '3.8'
services:
  nginx:
    build: ./requirements/nginx
    image: nginx:13
    container_name: nginx
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    env_file: .env
    restart: always
    ports:
      - "443:443"
    expose:
      - "443"

  mariadb:
    build: ./requirements/mariadb
    image: mariadb:13
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    expose:
      - "3306"

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:13
    container_name: wordpress
    restart: always
    env_file: .env
    depends_on:
      - mariadb

    volumes:
        - wordpress:/var/www/html
    expose:
      - "9000"
    networks:
      - inception

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/sel-jama/data/wordpress
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/sel-jama/data/mariadb

networks:
  inception:
    name: inception

